#!/bin/sh

clear

echo "  ____            _       _\n / ___|  ___ _ __(_)_ __ | |_ _   _ _ __ ___  ___\n \___ \ / __| '__| | '_ \| __| | | | '__/ _ \/ __|\n  ___) | (__| |  | | |_) | |_| |_| | | |  __/\__ \ \n |____/ \___|_|  |_| .__/ \__|\__,_|_|  \___||___/\n                   |_|\n"                            

echo ""
read -p "Please enter the Scripture you'd like to read here (e.g. 1 Nephi 1:1):  

" SCRIP
echo ""
echo ""

PULL=$(curl -s https://raw.githubusercontent.com/beandog/lds-scriptures/master/text/lds-scriptures.txt | grep -s "${SCRIP}" -m1 | fmt)


echo "${PULL}"
echo ""

