#!/bin/sh

# VARS
###################################################
LINK="https://raw.githubusercontent.com/beandog/lds-scriptures/master/text/lds-scriptures.txt"
COJC="https://www.churchofjesuschrist.org/"
###################################################

clear
while [ answer != "0" ]  
do 
clear

echo "  ____            _       _\n / ___|  ___ _ __(_)_ __ | |_ _   _ _ __ ___  ___\n \___ \ / __| '__| | '_ \| __| | | | '__/ _ \/ __|\n  ___) | (__| |  | | |_) | |_| |_| | | |  __/\__ \ \n |____/ \___|_|  |_| .__/ \__|\__,_|_|  \___||___/\n                   |_|\n"      
echo ""
echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
echo "Select from the following options: " 
echo ""
echo "1) Specific chapter and verse."
echo "2) Search for a keyword, or phrase."
echo "3) Learn more about the Church of Jesus Christ \n   of Latter-day Saints."
echo "4) Exit."
echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~" 
read -p "Choice: " answer 
clear
    case $answer in
    1) echo ""
       read -p "Please enter the Scripture you'd like to read here (e.g. 1 Nephi 1:1):  " SCRIP
       echo ""
       PULL=$(curl -s ${LINK} | grep -s --color='always' "${SCRIP}" -m1 | fmt)
       echo "${PULL}\n"
       
       read -p "Would you like to export the result to a file? [Yn]  " EXP
       case $EXP in
         [yY]) echo "Exporting to a text file..."
               sleep .5
               echo "${PULL}" | tee /home/$USER/"${SCRIP}".txt               
               echo "File is located here: /home/$USER/${SCRIP}.txt"
               ;;
         [nN]) ;;
       esac
       ;;
    2) echo ""
       read -p "Enter keyword or phrase here (e.g. Alma\ and\ Amulek):  " KEY
       echo ""
       KPULL=$(curl -s ${LINK} | grep --color='always' -w "${KEY}" | less -R | fold -s --width=70)
       
       echo "${KPULL}\n"
       
       read -p "Would you like to export the results to a file? [Yn]  " EXP2
       KPULL2=$(curl -s ${LINK} | grep --color='auto' -w "${KEY}" | less -R | fold -s --width=70)
       
       case $EXP2 in
         [yY]) echo "Exporting to a text file..."
               sleep .5
               echo "${KPULL2}" | tee /home/$USER/"${KEY}".txt
               echo "File is located here: /home/$USER/${KEY}.txt"
               ;;
         [nN]) ;;
       esac
       ;;
    3) echo ""
       echo "To learn more, please visit: ${COJC}\n"
       ;;
    4) break 
       ;;
   esac  
   echo "press RETURN for menu\n" 
   read key 
done 
exit 0    
