name: scriptures
adopt-info: scriptures
summary: Read the Standard Works of the Church of Jesus Christ of Latter-day Saints
description: |
  A simple way to read the Standard Works of the Church of Jesus Christ of Latter-day Saints. 
  English only.

  Special thanks to:
     * The LDS Documentation Project - https://scriptures.nephi.org/
     * @beandog for all the hard work that went into compiling the Scriptures.
       Without this work, this simple "app" wouldn't be possible.

  See also:
     * https://www.churchofjesuschrist.org/study/scriptures?lang=eng
     * https://www.churchofjesuschrist.org/study/scriptures/study-helps?lang=eng
     * https://scriptures.byu.edu/

license: MIT

base: core20
grade: stable
confinement: strict

apps:
  scriptures:
    command: bin/scriptures
    environment:
      LC_ALL: C.UTF-8
    plugs:
      - network
      
parts:
  scriptures:
    source: https://github.com/kz6fittycent/scriptures
    source-type: git
    plugin: nil
    
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version "$(git describe --tags | sed 's/^v//' | cut -d "-" -f1)"

    stage-packages:
      - curl
      
  publish:
    plugin: dump
    source: .
    organize:
      ./scriptures: /bin/scriptures
